sudo: required
services:
 - docker

before_install:
 - docker build -t darkelfio/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true darkelfio/react-test npm test

after_success:
  - docker build -t darkelfio/multi-client ./client
  - docker build -t darkelfio/multi-nginx ./nginx
  - docker build -t darkelfio/multi-server ./server
  - docker build -t darkelfio/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push darkelfio/multi-client
  - docker push darkelfio/multi-nginx
  - docker push darkelfio/multi-server
  - docker push darkelfio/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-210438197137
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
